### PR TITLE
fix(MarkedText): fix issue with escaping of 's' character

### PR DESCRIPTION
**Pull request by igorarkhipenko**
[ONEUI-263](https://jira.textkernel.nl/browse/ONEUI-263)

# Checklist
- [x] The implementation has been manually tested and complies with Textkernel [browser support guidelines](https://textkernel.com/browser-support/)
- [x] The implementation complies with [accessibility](CONTIRBUTING.md#accessibility) standards.
- [x] The component has a [displayName](CONTRIBUTING.md#display-names) defined.
- [x] The component comes with a detailed [PropTypes](CONTRIBUTING.md#component-props) (and defaultProps) definition.
- [x] Component PropTypes are sufficiently described / documented.
- [x] There is [a story](CONTRIBUTING.md#component-showcases) in Storybook.

### CODE REVIEW

**Comment by eszthoff** [comment]
@mukiienko there is something wrong with the Regex in this component. According to git logs you added it here, but there are no tests for it, so we are not clear on the requirements. Can you advise if we can remove `//s` or is it better to remove only `/`. Thanks

**Comment by carlobernardini** [comment]
Side note, LGTM has been complaining about this regex too: https://lgtm.com/projects/g/textkernel/oneui/snapshot/383b4f6e73cba2eef5af9f515f8078c2821b898e/files/src/components/Text/MarkedText/MarkedText.js?sort=name&dir=ASC&mode=heatmap#x790f12d8b3e564fa:1

**Comment by mukiienko** [comment]
> @mukiienko there is something wrong with the Regex in this component. According to git logs you added it here, but there are no tests for it, so we are not clear on the requirements. Can you advise if we can remove `//s` or is it better to remove only `/`. Thanks

We already discussed with Igor regarding `\\s`. I don't remember why do we need it. It looks like `\\s` was added by mistake and can be deleted. By the way, a good point about the tests, I've already added one for covering that case.

**Comment by mukiienko** [comment]
> Side note, LGTM has been complaining about this regex too: https://lgtm.com/projects/g/textkernel/oneui/snapshot/383b4f6e73cba2eef5af9f515f8078c2821b898e/files/src/components/Text/MarkedText/MarkedText.js?sort=name&dir=ASC&mode=heatmap#x790f12d8b3e564fa:1

I think we don't need '\\'. I'veve already deleted it.

**Review by eszthoff — APPROVED** [review]

**Pull request merged**
