### PR TITLE
feat(Toggle): migrate to new design

### PR DESCRIPTION
**Pull request by eszthoff**
Story: [ONEUI-449](https://textkernel.atlassian.net/browse/ONEUI-449)

### CODE REVIEW

**Comment by mukiienko** [comment]
@eszthoff, I think when element is focused, pushing enter button should toggle component.

**Comment by mukiienko** [comment]
@eszthoff Clicking on empty space switch the toggle. It looks strange:

https://github.com/user-attachments/assets/39b920f7-edb2-405e-8232-eb0604c94f51

**Comment by eszthoff** [comment]
> @eszthoff, I think when element is focused, pushing enter button should toggle component.

Do you have some accessibility guidelines that support that? 
I believe now it is work as a native checkbox would, and you need to press the space bar to move the toggle.

**Comment by mukiienko** [comment]
> > @eszthoff, I think when element is focused, pushing enter button should toggle component.
> 
> Do you have some accessibility guidelines that support that? I believe now it is work as a native checkbox would, and you need to press the space bar to move the toggle.

I thought the Enter key should also toggle the switch, but I was mistaken. The Space key works well.

**Comment by eszthoff** [comment]
> @eszthoff Clicking on empty space switch the toggle. It looks strange:

Not sure how you would like to address it. It is a "problem" with the story. Basically you are clicking on the empty label. In a real application the `div` would be smaller and hence it would not happen so much. Please advise

**Comment by mukiienko** [comment]
> > @eszthoff Clicking on empty space switch the toggle. It looks strange:
> 
> Not sure how you would like to address it. It is a "problem" with the story. Basically you are clicking on the empty label. In a real application the `div` would be smaller and hence it would not happen so much. Please advise

in the application level the div can be smaller, or not :) try to use `display: inline-flex;` for `Toggle` class.

**Review by mukiienko — APPROVED** [review]

**Pull request merged**
