### PR TITLE
feat(List, ListItem): add forwardRef option

### PR DESCRIPTION
**Pull request by eszthoff**

### CODE REVIEW

**Comment by carlobernardini** [comment]
@eszthoff can you provide a bit of context?

**Comment by eszthoff** [comment]
@carlobernardini I need to use ref for the list when implementing the multiselect in JF.

**Comment by carlobernardini** [comment]
@eszthoff Okay. I'm not sure `chore` would be the most appropriate type though. Also, [according to the React docs](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers) this should formally be treated as a breaking change (even though for now it wouldn't make a big difference)

**Comment by eszthoff** [comment]
BREAKING CHANGES: forwardRef applied to List component

**Pull request merged**
