### PR TITLE
feat: add custom types

### PR DESCRIPTION
**Pull request by PavelKirvelTextkernel**
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. Use imperative, present tense in your commit description ("change", not "changed" or "changes") without uppercases or period (.) at the end.

# Checklist
- [ ] The implementation has been manually tested and complies with Textkernel [browser support guidelines](https://textkernel.com/browser-support/)
- [ ] The implementation complies with [accessibility](CONTIRBUTING.md#accessibility) standards.
- [ ] The component has a [displayName](CONTRIBUTING.md#display-names) defined.
- [ ] The component comes with a detailed [PropTypes](CONTRIBUTING.md#component-props) (and defaultProps) definition.
- [ ] Component PropTypes are sufficiently described / documented.
- [ ] There is [a story](CONTRIBUTING.md#component-showcases) in Storybook.

### CODE REVIEW

**Comment by PavelKirvelTextkernel** [comment]
After some investigation:
1. We can copy current types.d.ts to build folder but in this case we will  have red highlights(we can check type value, need to check in another app is it possible to jump in types.d.ts).
2. Rewrite typs.d.ts to types.ts/customTypes.ts and add importing where we use them.

**Comment by mukiienko** [comment]
> After some investigation:
> 
> 1. We can copy current types.d.ts to build folder but in this case we will  have red highlights(we can check type value, need to check in another app is it possible to jump in types.d.ts).
> 2. Rewrite typs.d.ts to types.ts/customTypes.ts and add importing where we use them.

Hi, I didn't get your comment. How is it related with 3rd party libraries, for example, react-model?

**Comment by PavelKirvelTextkernel** [comment]
About types: 
https://stackoverflow.com/questions/51983175/usage-of-types-and-interface-without-importing

**Comment by PavelKirvelTextkernel** [comment]
For global type(without importing) i've tried this: export type EmptyElement = false | null | undefined;

declare global {
    // eslint-disable-next-line @typescript-eslint/naming-convention
    type emp = EmptyElement;
}
But still get red highlight

**Pull request merged**
